// Generated by Wrangler by running `wrangler types`

interface Env {
	BOT_INFO: {"id":7814941456,"is_bot":true,"first_name":"puniru bot","username":"puniru_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":true,"can_connect_to_business":false,"has_main_web_app":false};
	URL: "https://puniru-bot.arcohol.workers.dev/";
	VOICE: [{"title":"puni!","file":"puni!.ogg"},{"title":"puni!!","file":"puni!!.ogg"},{"title":"puni!!!","file":"puni!!!.ogg"},{"title":"ni!","file":"ni!.ogg"},{"title":"jyan!","file":"jyan!.ogg"},{"title":"punia!","file":"punia!.ogg"}];
	BOT_TOKEN: string;
}
